'DLC: Shattered Space':
    - '/(Which DLC\(s\) do you have installed\?\n\n.*Shattered Space.*\n\n###)/m'
'Platform: PC (Steam)':
    - '/(Which platform are you playing on\?\n\nPC \(Steam\)\n\n###)/m'
'Type: Animations':
    - '/(Which category represents the issue you are reporting\?\n\nAnimations.*\n\n###)/m'
'Type: Audio':
    - '/(Which category represents the issue you are reporting\?\n\nAudio.*\n\n###)/m'
'Type: Interface':
    - '/(Which category represents the issue you are reporting\?\n\nInterface.*\n\n###)/m'
'Type: Items':
    - '/(Which category represents the issue you are reporting\?\n\nItems.*\n\n###)/m'
'Type: Locations':
    - '/(Which category represents the issue you are reporting\?\n\nLocations.*\n\n###)/m'
'Type: Meshes':
    - '/(Which category represents the issue you are reporting\?\n\nMeshes.*\n\n###)/m'
'Type: Missions & Dialogue':
    - '/(Which category represents the issue you are reporting\?\n\nMissions & Dialogue.*\n\n###)/m'
'Type: NPCs':
    - '/(Which category represents the issue you are reporting\?\n\nNPCs.*\n\n###)/m'
'Type: Outposts':
    - '/(Which category represents the issue you are reporting\?\n\nOutposts.*\n\n###)/m'
'Type: Perks & Skills':
    - '/(Which category represents the issue you are reporting\?\n\nPerks & Skills.*\n\n###)/m'
'Type: Placed Objects':
    - '/(Which category represents the issue you are reporting\?\n\nPlaced Objects.*\n\n###)/m'
'Type: Scripts':
    - '/(Which category represents the issue you are reporting\?\n\nScripts.*\n\n###)/m'
'Type: Ships':
    - '/(Which category represents the issue you are reporting\?\n\nShips.*\n\n###)/m'
'Type: Textures':
    - '/(Which category represents the issue you are reporting\?\n\nTextures.*\n\n###)/m'